// <auto-generated />
namespace Kaizen.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PositionNameFixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PositionNameFixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201903102004509_PositionNameFixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
